[general]
import = [
  "./catpuccin-mocha.toml"
]
[font]
size = 12.0
normal = {family = "FiraCode Nerd Font"}
[keyboard]
bindings = [
   { key = "T", mods = "Control|Shift", action = "SpawnNewInstance" }
]
[window]
opacity = 1.0
blur = true
