include ./window_rules.conf
set $mod Mod4
set $alt Mod1
floating_modifier $mod

set $refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioMicMute exec --no-startup-id ~/.config/dunst/volume_brightness.sh mic_mute
bindsym XF86AudioRaiseVolume exec --no-startup-id ~/.config/dunst/volume_brightness.sh volume_up
bindsym XF86AudioLowerVolume exec --no-startup-id ~/.config/dunst/volume_brightness.sh volume_down
bindsym XF86AudioMute exec --no-startup-id ~/.config/dunst/volume_brightness.sh volume_mute

bindsym XF86MonBrightnessUp exec --no-startup-id ~/.config/dunst/volume_brightness.sh brightness_up
bindsym XF86MonBrightnessDown exec --no-startup-id ~/.config/dunst/volume_brightness.sh brightness_down

bindsym $mod+Return exec kitty --title="Terminal"
bindsym $mod+Shift+Return exec kitty --title="Terminal" --class="term-float"
bindsym $mod+P xrandr --output HDMI-1-0 --auto --right-of eDP-1
bindsym $mod+q kill

bindsym $mod+space exec --no-startup-id rofi run -show drun -dpi 1
bindsym $mod+c exec --no-startup-id rofi run -show calc -no-show-match -no-sort
bindsym $mod+Shift+S exec --no-startup-id flameshot gui
# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
bindsym $mod+Shift+w exec --no-startup-id bash ~/dotfiles/scripts/wallpaper-rofi.sh
bindsym $mod+f fullscreen toggle

bindsym $mod+t layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+s layout toggle split
bindsym $mod+Shift+f floating toggle
bindsym $mod+Shift+B exec blueman-manager
bindsym $mod+d focus mode_toggle
bindsym $mod+e exec --no-startup-id thunar
bindsym $mod+a focus parent
bindsym $mod+b exec --no-startup-id helium-browser
bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart
bindsym $mod+Shift+e exec i3-msg exit

mode "resize" {
        bindsym h resize shrink width 10 px or 10 ppt
        bindsym j resize grow height 10 px or 10 ppt
        bindsym k resize shrink height 10 px or 10 ppt
        bindsym l resize grow width 10 px or 10 ppt

        bindsym Return mode "default"
}

bindsym $mod+r mode "resize"
