font_size 12.0

cursor_shape block

cursor_shape_unfocused hollow

scrollback_lines 10000 

enable_audio_bell no

background_opacity 0.8

background_blur 1

linux_display_server auto

wayland_enable_ime yes

cursor_trail 100

cursor_trail_decay 0.2 0.2

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
#
confirm_os_window_close 0
clipboard_control write-clipboard write-primary read-clipboard read-primary


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
